import type { FakePart } from "./fake-ul-data"

const textEncoder = new TextEncoder()
const crcTable = makeCrcTable()

export function createKiCadZip(part: FakePart, version: string): Uint8Array {
  const root = `KiCADv${version}`
  const timestamp = "20260529T000000"
  const footprintName = `FAKE_GENERATED_${part.pin_count}PIN_PLACEHOLDER`
  const symbolName = `FAKE_GENERATED_${sanitizeKiCadName(part.mpn)}`

  return zipFiles([
    {
      path: `${root}/${timestamp}.kicad_sym`,
      data: generateSyntheticKiCadSymbol({
        symbolName,
        footprintName,
        requestedMpn: part.mpn,
      }),
    },
    {
      path: `${root}/footprints.pretty/${footprintName}.kicad_mod`,
      data: generateSyntheticKiCadFootprint({
        footprintName,
        pinCount: part.pin_count,
        requestedMpn: part.mpn,
      }),
    },
    {
      path: `${root}/README.txt`,
      data: `\
This archive is generated by fake-ul-kicad-proxy for integration tests.
It is synthetic placeholder CAD, not third-party vendor CAD output.
Requested MPN: ${part.mpn}
`,
    },
  ])
}

export function createStepZip(part: FakePart): Uint8Array {
  const stepFileName = getSyntheticStepFileName(part)

  return zipFiles([
    {
      path: stepFileName,
      data: generateSyntheticStepModel({
        fileName: stepFileName,
        requestedMpn: part.mpn,
      }),
    },
  ])
}

interface SymbolOptions {
  symbolName: string
  footprintName: string
  requestedMpn: string
}

function generateSyntheticKiCadSymbol(options: SymbolOptions): string {
  return `\
(kicad_symbol_lib (version 20211014) (generator fake-ul-kicad-proxy)
  (symbol "${options.symbolName}" (pin_names (offset 1.016)) (in_bom yes) (on_board yes)
    (property "Reference" "U" (at 0 5.08 0))
    (property "Value" "${options.symbolName}" (at 0 -5.08 0))
    (property "Requested_MPN" "${options.requestedMpn}" (at 0 -7.62 0))
    (property "Footprint" "Generated:${options.footprintName}" (at 0 -10.16 0))
    (property "Fake_CAD_Notice" "Synthetic placeholder generated for tests; not vendor CAD." (at 0 -12.7 0))
  )
)
`
}

interface FootprintOptions {
  footprintName: string
  pinCount: number
  requestedMpn: string
}

function generateSyntheticKiCadFootprint(options: FootprintOptions): string {
  const pads = Array.from({ length: options.pinCount }, (_, index) => {
    const pin = index + 1
    const side = index < options.pinCount / 2 ? -1 : 1
    const rowIndex =
      index < options.pinCount / 2 ? index : options.pinCount - index - 1
    const x = side * 3.81
    const y = -3.81 + rowIndex * 2.54
    const shape = pin === 1 ? "rect" : "oval"

    return `  (pad "${pin}" thru_hole ${shape} (at ${formatMm(x)} ${formatMm(y)}) (size 1.5 1.5) (drill 0.8) (layers "*.Cu" "*.Mask"))`
  }).join("\n")

  return `\
(footprint "${options.footprintName}" (version 20221018) (generator fake-ul-kicad-proxy)
  (descr "Synthetic placeholder footprint for integration tests; not vendor CAD.")
  (tags "fake generated placeholder")
  (attr through_hole)
  (fp_text reference "REF**" (at 0 -6.35) (layer "F.SilkS"))
  (fp_text value "${options.footprintName}" (at 0 6.35) (layer "F.Fab"))
  (fp_text user "Requested MPN: ${options.requestedMpn}" (at 0 8.89) (layer "Cmts.User"))
  (fp_line (start -5.08 -5.08) (end 5.08 -5.08) (stroke (width 0.12) (type solid)) (layer "F.SilkS"))
  (fp_line (start 5.08 -5.08) (end 5.08 5.08) (stroke (width 0.12) (type solid)) (layer "F.SilkS"))
  (fp_line (start 5.08 5.08) (end -5.08 5.08) (stroke (width 0.12) (type solid)) (layer "F.SilkS"))
  (fp_line (start -5.08 5.08) (end -5.08 -5.08) (stroke (width 0.12) (type solid)) (layer "F.SilkS"))
${pads}
)
`
}

function generateSyntheticStepModel(options: {
  fileName: string
  requestedMpn: string
}): string {
  return `\
ISO-10303-21;
HEADER;
FILE_DESCRIPTION(('Synthetic placeholder STEP generated for tests; not vendor CAD.'), '2;1');
FILE_NAME('${options.fileName}', '2026-06-12T00:00:00', ('fake-ul-kicad-proxy'), ('tscircuit'), '', '', '');
FILE_SCHEMA(('CONFIG_CONTROL_DESIGN'));
ENDSEC;
DATA;
/* Requested MPN: ${options.requestedMpn} */
ENDSEC;
END-ISO-10303-21;
`
}

function getSyntheticStepFileName(part: FakePart): string {
  if (part.pin_count === 8 && part.package.includes("through-hole")) {
    return "DIP8_300.step"
  }

  return `FAKE_GENERATED_${part.pin_count}PIN.step`
}

function sanitizeKiCadName(value: string): string {
  return value.replace(/[^A-Za-z0-9_]/g, "_")
}

function formatMm(value: number): string {
  return Number.isInteger(value) ? value.toFixed(0) : value.toFixed(2)
}

interface ZipFile {
  path: string
  data: string
}

function zipFiles(files: ZipFile[]): Uint8Array {
  const chunks: Uint8Array[] = []
  const centralDirectory: Uint8Array[] = []
  let offset = 0

  for (const file of files) {
    const name = textEncoder.encode(file.path)
    const data = textEncoder.encode(file.data)
    const crc = crc32(data)

    const localHeader = new Uint8Array(30 + name.length)
    const localView = new DataView(localHeader.buffer)
    localView.setUint32(0, 0x04034b50, true)
    localView.setUint16(4, 20, true)
    localView.setUint16(10, 0, true)
    localView.setUint32(14, crc, true)
    localView.setUint32(18, data.length, true)
    localView.setUint32(22, data.length, true)
    localView.setUint16(26, name.length, true)
    localHeader.set(name, 30)
    chunks.push(localHeader, data)

    const centralHeader = new Uint8Array(46 + name.length)
    const centralView = new DataView(centralHeader.buffer)
    centralView.setUint32(0, 0x02014b50, true)
    centralView.setUint16(4, 20, true)
    centralView.setUint16(6, 20, true)
    centralView.setUint16(12, 0, true)
    centralView.setUint32(16, crc, true)
    centralView.setUint32(20, data.length, true)
    centralView.setUint32(24, data.length, true)
    centralView.setUint16(28, name.length, true)
    centralView.setUint32(42, offset, true)
    centralHeader.set(name, 46)
    centralDirectory.push(centralHeader)

    offset += localHeader.length + data.length
  }

  const centralDirectoryOffset = offset
  const centralDirectorySize = centralDirectory.reduce(
    (sum, chunk) => sum + chunk.length,
    0,
  )
  const end = new Uint8Array(22)
  const endView = new DataView(end.buffer)
  endView.setUint32(0, 0x06054b50, true)
  endView.setUint16(8, files.length, true)
  endView.setUint16(10, files.length, true)
  endView.setUint32(12, centralDirectorySize, true)
  endView.setUint32(16, centralDirectoryOffset, true)

  return concatUint8Arrays([...chunks, ...centralDirectory, end])
}

function concatUint8Arrays(chunks: Uint8Array[]): Uint8Array {
  const result = new Uint8Array(
    chunks.reduce((sum, chunk) => sum + chunk.length, 0),
  )
  let offset = 0

  for (const chunk of chunks) {
    result.set(chunk, offset)
    offset += chunk.length
  }

  return result
}

function makeCrcTable(): Uint32Array {
  const table = new Uint32Array(256)

  for (let i = 0; i < table.length; i++) {
    let crc = i
    for (let bit = 0; bit < 8; bit++) {
      crc = crc & 1 ? 0xedb88320 ^ (crc >>> 1) : crc >>> 1
    }
    table[i] = crc >>> 0
  }

  return table
}

function crc32(data: Uint8Array): number {
  let crc = 0xffffffff

  for (const byte of data) {
    crc = (crcTable[(crc ^ byte) & 0xff] ?? 0) ^ (crc >>> 8)
  }

  return (crc ^ 0xffffffff) >>> 0
}
